### ISSUE TITLE
Enabling OKTA autentication SF_USERNAME

### ISSUE THREAD

**Issue by jeyanandcse** [Snowflake-Labs/schemachange#103]
Hi,

We are using OKTA authentication to login to the Snowflake.
How to enable OKTA authentication for the SF_USERNAME parameter?

**Comment by sfc-gh-jhansen** [comment]
Hey there @jeyanandcse, schemachange doesn't support SSO. It is generally run in CI/CD pipelines in a non-interactive mode using a service account.
