### ISSUE TITLE
Option to avoid the R__ checksum check

### ISSUE THREAD

**Issue by shaundodimead** [Snowflake-Labs/schemachange#105]
For reasons, we're looking to schemachange to run batch SQL scripts, because, well, snowflake wont. We have a team used to writing multiple SQL statements in one script which would normally hit a stored proc, but, well, you know the rest.

I've wrapped a CLI app around this and its working pretty well, but we're looking to trigger R__ scripts (as alternatives to multi-statement stored procs) via lamda, and the checksum test quite rightly skips R__ scripts it thinks match the last time it ran.

If I submitted a PR with --no-checksum-check would you accept it?

**Comment by sfc-gh-jhansen** [comment]
Hi there @shaundodimead, thanks for raising the issue. snowchange already supports the use-case you're describing, with the "A"lways scripts (A__ scripts). Please see the schemachange documentation for more details.

**Comment by shaundodimead** [comment]
Yup that is exactly what I need, I even read over that bit of the docs. It was late... !
