### ISSUE TITLE
Can any one explain the difference between schmeachnage vs liquibase vs flyway

### ISSUE THREAD

**Issue by abhi-dwivedi** [Snowflake-Labs/schemachange#109]
Hi Team,

Can any one explain the difference between schmeachnage vs liquibase vs flyway

Why we use shemachnage

**Comment by abhi-dwivedi** [comment]
any one gives any update

**Comment by sfc-gh-jhansen** [comment]
Hi there @abhi-dwivedi, please check out my [DevOps Recommendations when Building on Snowflake](https://developers.snowflake.com/resources/?wvideo=haqeh4q2se) recording for more details.
