### ISSUE TITLE
Please support OAuth2 authentication method

### ISSUE THREAD

**Issue by spoutrain** [Snowflake-Labs/schemachange#119]
Hi !

**Problem description**
Password and Key-Pair authentication mechanisms are not sufficient:
- Password authentication puts Snowflake as the system of record of user's credentials, which can be against policies in some companies where user's credentials must be managed by a central system
- Key-Pair authentication does not allow usage of MFA, which can be important in some organizations as well

Moreover, since such credentials need to be stored in environment variables, this pose some security risks.

**Proposed solution**
The Snowflake Python connector natively supports the externalbrowser authentication method, which basically asks the user to authenticate through a browser window managed by Snowflake, instead of having such credentials stored in an environment variable. This would be a short, easy and elegant way of solving above-mentioned issues.

Thanks for reading this post, and I love your tool !

**Comment by umarh-ccy** [comment]
so I had the same issue as you and dug into the source code - the lib uses the snowflake python connector under the hood which supports a number of sign on methods (SSO, MFA, and Key based authentication) so I'd recommend going down that route and perhaps pushing a PR. Personally, I went with a key-based method which works perfectly.

**Comment by MACKAT05** [comment]
I have a start on a fork that covers this here: https://github.com/MACKAT05/schemachange/
its not ready for a pull request but it illustrates the basics of the security change; 
@jeremiahhansen Is it okay of Oauth can only be supported when a Yaml File is present? I cannot think of an encompassing way to support  every oauth providers required configurations in any reasonable way through the CLI interface

**Comment by podung** [comment]
@MACKAT05 thanks - I'm trying out your fork now.  If I can help on anything let me know on getting this moved forward

**Comment by sfc-gh-jhansen** [comment]
Hey there @MACKAT05, so sorry for the delay. I took a look at your changes in the fork and think they look great.

I was thinking about how to best deal with the 4 different auth options. It looks like your current solution depends on the presence of the `SNOWFLAKE_AUTHENTICATOR` environment variable, which is at least consistent with how we're doing it today (looking for specific environment variables). We may be able to refactor again and make this more simple/consistent in the future, but looks like a great start and adds some needed functionality.

Please submit a PR for this!

**Comment by sfc-gh-tmathew** [comment]
@MACKAT05 When will you be raising the PR for this? I am working on adding the Programmatic SSO portion and does not have the level of refactoring you have here. I am planning to raise a PR for 3.4.3 just for the Okta authentication.

**Comment by sfc-gh-tmathew** [comment]
Thank you @MACKAT05 for the contribution to v3.5.0 release to include OAuth.

Hello @spoutrain, @umarh-ccy 

The latest v3.6.0 includes the OAuth Authentication option. 

Closing this issue for now. Please open a new issue if you find any gaps in the OAuth Option.
