### ISSUE TITLE
Deprecated API Calls

### ISSUE THREAD

**Issue by charton11** [Snowflake-Labs/schemachange#122]
Hey,
I love the code that has been released and it works great. I was wondering if the deprecation of v1 API calls to Snowflake will break this code? I have seen where you make the calls, and very soon these calls will not be valid.

Has anyone else seen this or been worried about these coming changes? I may be completely off base, but I wanted to bring it up and see.

Thanks,
Christopher

**Comment by sfc-gh-jhansen** [comment]
Hey there @charton11, I assume that you're asking about the Snowflake REST API feature, and no that has no impact on schemachange. schemachange uses the Snowflake Python connector not the new REST API reature.
