### ISSUE TITLE
Snowflake - code compiling, testing & pushing the code to GIT Repo using any client 

### ISSUE THREAD

**Issue by praneeth1987** [Snowflake-Labs/schemachange#126]
We are planning to using Visual studio code to push the code to GIT repo in Azure DevOps, but unfortunately we don't have snowflake code compiler and testing available in Visual Studio code.

DO you recommend any tool where we can compile, test the Snowflake code push the code to GIT repo in Azure DevOps? To avoid manual copy/paste into Visual Studio code from Snowflake console or SnowSQL?

**Comment by sfc-gh-jhansen** [comment]
Hey there @praneeth1987, I would suggest testing out our new Visual Studio Code plugin. It's currently in Private Preview but will be in Public Preview soon. In the meantime please reach out to your Snowflake account team about getting access to the PrPr.
