### ISSUE TITLE
Repository still alive?

### ISSUE THREAD

**Issue by CermitDFrog** [Snowflake-Labs/schemachange#129]
@jeremiahhansen @sfc-gh-jhansen is the repository still being maintained? I'm currently using this in a production setting and would like to contribute.

**Comment by sfc-gh-jhansen** [comment]
Hey there @CermitDFrog, so sorry for the delay here. Yes, this repo and project are still being maintained. I've just been really busy lately and not able to give it the attention it deserves. What changes do you have in mind?

**Comment by CermitDFrog** [comment]
Hey thanks for the reply. Our use case involves calling the API for
specific areas of our repository and I calling schemachange using
subprocess.

I'd prefer not to use subprocess so I want to clean up the internal API so
that it's friendlier when calling from inside a python script.

**Comment by EdHodgkinson-IOPP** [comment]
Hi @CermitDFrog, I've been doing the following (not in production, but have been doing it locally against development clones for a few months).

import schemachange.cli as sc
I then build up an array listing the arguments, and then pass that into sc.main().

**Comment by shaundodimead** [comment]
Yup, we're doing exactly the same thing
