### ISSUE TITLE
Upgrade to snowflake-connector 3.0.0 and maybe 3.11?

### ISSUE THREAD

**Issue by shaundodimead** [Snowflake-Labs/schemachange#144]
Sorry to be that guy who turns up with this without a PR, but it'd be super handy to upgrade the deps for 3.11 happiness...

**Comment by svitty** [comment]
Agreed! we are currently blocked from upgrading other dependencies for this very reason!

**Comment by afeld** [comment]
cc https://github.com/Snowflake-Labs/schemachange/issues/165

**Comment by sfc-gh-twhite** [comment]
This was resolved with #165.
