### ISSUE TITLE
Github Workflow test.yml

### ISSUE THREAD

**Issue by kplgrwl** [Snowflake-Labs/schemachange#146]
Hi Team, 

I have some experience with using Schemachange on one of my earlier project. Now I am trying to set schemachange up again for another project that I am working on. The github\workflows\test.yml keeps failing on 'Test with pytest' step. There is no change promoted yet. Please advice. 

![image](https://user-images.githubusercontent.com/78981499/217626602-cfa2e0eb-00ea-4a62-9f1a-3920260ffbca.png)

Part of log - 
![image](https://user-images.githubusercontent.com/78981499/217627071-2a7339c9-33a2-46fc-afa6-a3a31e69e60a.png)

**Comment by sfc-gh-jhansen** [comment]
Hey there @kplgrwl, that GitHub Actions workflow is only for the schemachange project itself. It sounds like you may be cloning the schemachange project and working from there? If so, that's not the intended use of the tool. It's deployed via PyPI and can be simply pip installed and used by your own GitHub Actions workflow in your own project.

Please check out this Quickstart for the details: https://quickstarts.snowflake.com/guide/devops_dcm_schemachange_github/index.html?index=..%2F..index#0
