### ISSUE TITLE
Version 3.5.1 broke for all deployments with Verbose logging and R__ scripts

### ISSUE THREAD

**Issue by CermitDFrog** [Snowflake-Labs/schemachange#151]
On line 544 there is a log for R__ scripts that are skipped. With 3.5.0/5.1 there was a change that resulted in the parameter not being passed correctly for format. Now all our deployments are getting a key error and halting on this line.

![image](https://user-images.githubusercontent.com/42278133/218471549-95d62122-b372-4611-b5c6-0bbd38e06207.png)

Correction should be to switch line 544 to the following
```python
          print(_log_skip_r.format(**script))
```

I can't make a PR without destroying my current branch and PR, but I will be including this change in my branch.

**Comment by CermitDFrog** [comment]
[PR 150](https://github.com/Snowflake-Labs/schemachange/pull/150) includes this change as well.

**Comment by CermitDFrog** [comment]
@sfc-gh-jhansen Looks like multiple folks have run into this issue. Could we get my PR merged to resolve?

I had to revert my production usage version back to 3.4.2 in the meantime.

**Comment by sfc-gh-jhansen** [comment]
Just released 3.5.2 with only the verbose logging fix for now. I just didn't have time tonight to think about and test out your new changes. But I will shortly!
