### ISSUE TITLE
Storage file of V1 schema details before upgrading to V2

### ISSUE THREAD

**Issue by MallikarjunGattupally** [Snowflake-Labs/schemachange#155]
Hi guys, I wanted to know that, does the old schema is saved before it is upgraded to new version.
If YES, where is it saved and
if NO, can we store the previous schema details.

PS: I know versioning data is saved in HISTORY_TABLE. I need the entire schema storage.
And how can we rollback if needed. 
Thanks in advance !!

**Comment by sfc-gh-jhansen** [comment]
Hi there @MallikarjunGattupally, schemachange does not automatically save the previous version of the database objects (and I'm not aware of any database change management tool that does). For rollbacks we recommend a "roll forward" approach. So create a new versioned script, add the DDL/DML to fix the issues, then deploy. Hope that helps.
