### ISSUE TITLE
No tagging of repository versions

### ISSUE THREAD

**Issue by temyers** [Snowflake-Labs/schemachange#170]
**Actual**
This repository does not use tagging.  

This makes any cross referencing of the source with version history, and understanding detailed changes between versions hard.

**Expected**
For every [release](https://pypi.org/project/schemachange/#history) there should be a corresponding repository tag with the source for that version.

**Comment by bcw1000** [comment]
Please tag releases.

**Comment by sfc-gh-jhansen** [comment]
We are now using releases, thanks for the suggestion!
