### ISSUE TITLE
schemachange gives <EOF> error executing DDL for tasks with multiple statements wrapped by !set_delimiter

### ISSUE THREAD

**Issue by rbusch45** [Snowflake-Labs/schemachange#171]
I tried multiple syntactical approaches for creating tasks with multiple SQL statements in a migration script.
This example from Snowflake docs does not work:

!set sql_delimiter=/
CREATE OR REPLACE TASK METADATA.ROOT_TASK
    WAREHOUSE = COMPUTE_WH
    WHEN SYSTEM$STREAM_HAS_DATA('METADATA.TRIGGER_STREAM')
AS
BEGIN
    call METADATA.INIT_ETL_RUN('Y');
END;
!set sql_delimiter=";"

The work around I found is this:

CREATE OR REPLACE TASK METADATA.ROOT_TASK
    WAREHOUSE = COMPUTE_WH
    WHEN SYSTEM$STREAM_HAS_DATA('METADATA.TRIGGER_STREAM')
AS
EXECUTE IMMEDIATE
$$
BEGIN
    call METADATA.INIT_ETL_RUN('Y');
END;
$$
;

is/will !set_delimiter (be) supported by schemachange? 

other suggestions?

**Comment by sfc-gh-jhansen** [comment]
Hey all. The primary issue here is that !set sql_delimiter is a snowsql specific thing. Did the advice @tsceurman-ara gave help?
