### ISSUE TITLE
Does this repo still maintain?

### ISSUE THREAD

**Issue by carelessrevamper** [Snowflake-Labs/schemachange#179]
I love this tool, and really have ideas how to make it better, I can help since I'm a python developer. 
I just want to make sure this repo haven't been deprecated.

Thanks!

**Comment by afeld** [comment]
cc https://github.com/Snowflake-Labs/schemachange/issues/129

**Comment by sfc-gh-jhansen** [comment]
Yes, this repo is still active, and I apologize for the slow response here, just been wicked busy with work :).
