### ISSUE TITLE
Microsoft SQL Server Support?

### ISSUE THREAD

**Issue by hnipen** [Snowflake-Labs/schemachange#198]
Hello team, we are looking into new deployment options for Snowflake and also Microsoft SQL Server
Is there a possible way to configure schemachange in order to target deployments towards SQL Server? :-)

**Comment by sfc-gh-tmathew** [comment]
Hello @hnipen 

Thank you for reaching out. Unfortunately, schemachange was built to work with snowflake only.

We do not have plans for supporting any databases other than Snowflake at this time.
