### ISSUE TITLE
Schemachange render: error: argument --vars: invalid loads value: '{variable1: value1, variable2: value2}'

### ISSUE THREAD

**Issue by lgc-jacovanwyk** [Snowflake-Labs/schemachange#202]
For the life of me, I cannot work out how to pass these variables? I run the following:
`schemachange render -a XXX.eu-west-1 -u XXX -r XXX -w XXX --vars '{"variable1": "value1", "variable2": "value2"}' `
But repeatedly getting this error back:
`schemachange render: error: argument --vars: invalid loads value: '{variable1: value1, variable2: value2}'`

I've lifted the variables as is from the documentation. Is this a bug?

**Comment by sfc-gh-tmathew** [comment]
When using the render command, you do not need the options used for deploy.

When I run your command using 3.6.0, I get the following message 

```text
usage: schemachange [-h] {deploy,render} ...
schemachange: error: unrecognized arguments: -a -u XXX -r XXX -w XXX
```

For example, run the help command to see the options expected for the render command
```bash
schemachange render -h
```

Here is a sample file that have in my folder say `R__test.sql`
```sql
SET MY_VARIABLE = {{ my_value }}
SET MY_VARIABLE2 = {{ my_second_value }}
```

If I run the command to render the variables 

`schemachange render --vars '{"my_value":"foobar", "my_second_value":"foobar2"}' ./*`

Output shown below (With some output truncated or obfuscated)
```text
schemachange version: 3.6.0
Using root folder /Users/<user>/repos/schemachange-demo
Using variables:
  my_value: foobar
  my_second_value: foobar2

Checksum 1bd96...b781aedc
SET MY_VARIABLE = foobar
SET MY_VARIABLE2 = foobar2
```

I checked this with 3.5.3 and 3.6.0 and we have the same behavior via zsh shell. 

Please confirm if you are able to render the scripts by using the expected syntax.

**Comment by pravinwadikar** [comment]
Please use --var "{""variable1"": ""value1"", ""variable2"": ""value2""}". It will work.

**Comment by sfc-gh-tmathew** [comment]
This works as designed. Closing the issue
