### ISSUE TITLE
Log session ID in the output 

### ISSUE THREAD

**Issue by opodoprigora** [Snowflake-Labs/schemachange#243]
**Is your feature request related to a problem? Please describe.**
It's difficult to troubleshoot SC runs when no session id is available and query history table needs to be searched for text instead. 

**Describe the solution you'd like**
Log session id in the output. Additionally it would be helpful to have this available via a default execution and to not have to use verbose argument. 

**Describe alternatives you've considered**
Searching for SQL text in the query history table. 

**Additional context**
Session ID can be retrieved using `SELECT CURRENT_SESSION()`.

**Comment by opodoprigora** [comment]
[PR opened](https://github.com/Snowflake-Labs/schemachange/pull/245)

**Comment by sfc-gh-tmathew** [comment]
Thank you for your contribution @opodoprigora. The changes have been pushed to 3.7.0
