### ISSUE TITLE
Separator 

### ISSUE THREAD

**Issue by qqcvd** [Snowflake-Labs/schemachange#26]
Hello

I think there is an issue with the naming pattern taken into account by the python.
The file must be named : V1.1.1__Hello_World.sql
Thus, the version extracted will be "V1.1.1" (it is the version number before the double underscore)

But if the file is named : V1.1.1__Hello_World__My_First_Script.sql
The version will be "V1.1.1__Hello_World" instead of "V1.1.1"

Best Regards

**Comment by sfc-gh-jhansen** [comment]
The naming convention for snowchange (and Flyway, on which it's based) is specifically to only have one set of double underscores, which is used to separate the version from the description. The description is only supposed to have a single set of underscores. Next time I make changes to the documentation I will add a note warning against this.

**Comment by sfc-gh-jhansen** [comment]
Hey @qqcvd, sorry for the slow response. I do see the bug here. If you'd be willing to make the fixes and submit a PR I'd be happy to review.

**Comment by sfc-gh-jhansen** [comment]
This issues is resolved in version 3.0.0
