### ISSUE TITLE
error Logging with Line Number of .sql File  

### ISSUE THREAD

**Issue by srinirama** [Snowflake-Labs/schemachange#30]
Hi,

Im evaluating this tool for our DB Version Control . One feature i feel missing is that  , how do i debug what portion/Line Number of sql (e.g V1.2__load_tables_from_s3.sql) caused the error ? Im unable to find it across from the documentation provided

**Comment by sfc-gh-jhansen** [comment]
Hi there @srinirama, thanks for reaching out! That's a great question, not sure how to best handle that. I recently added changes that add a query tag to indicate which Snowflake queries are issued by which script. But from the snowchange side, I agree that this would be a nice feature. Any ideas about how to update the code to capture these details? Please feel free to submit a PR with the details!

**Comment by tykishore-snowflake** [comment]
Can you please elaborate more on how to leverage Query tag feature?

**Comment by sfc-gh-jhansen** [comment]
The queries run from snowchange include a query tag, and that includes the change script name. This can be used for a variety of purposes. They can be found/queried in the [QUERY_HISTORY View](https://docs.snowflake.com/en/sql-reference/account-usage/query_history.html) as well as the [QUERY_HISTORY Table Functions](https://docs.snowflake.com/en/sql-reference/functions/query_history.html).

**Comment by yadutata** [comment]
That is wonderful. Now I see that. Can this be overwritten from the script etc? My Health care customer wanted to tag all the deployments associated with a  Particular Release ( ex: Commercial Release R1)? Is this possible? Also do you have any guidelines in following the naming conventions ( like does it have to be always starting with V1 etc?) Appreciate your input

**Comment by sfc-gh-jhansen** [comment]
Yeah, you could customize the logic in the script to send different/additional data in the query tag.

And as for the naming conventions I believe you're asking about the file naming conventions? Please check out the documentation (README) for the details, but they're spelled out there. A versioned migration file must always start with a capital V and be followed by the version number and then the rest.

**Comment by sfc-gh-jhansen** [comment]
Hey @srinirama, sorry for the slow response here. Hopefully the new query tag feature was able to address your concerns. But if you still think it would be helpful to capture the (starting) line number from the change script please go ahead and submit a PR with those changes. I'd be happy to review.
