### ISSUE TITLE
Request/Clarification for Failure logging

### ISSUE THREAD

**Issue by yadutata** [Snowflake-Labs/schemachange#31]
We are evaluating the usage of this for our deployments with snowflake. During our initial testing, we found that when the Jenkins Pipeline fails, ( Lets say one sql in one of the script failed) or one of the script failed. We don't see the metadata being updated in snowflake (CHANGE_HISTORY) as failed. Only the successful ones are being updated. Can you please clarify?

**Comment by sfc-gh-jhansen** [comment]
Hey there @yadutata, thanks so much for the idea. You're right that snowchange doesn't currently log any failures. If you have ideas to make snowchange better in this area, would welcome your assistance. Would appreciate any suggestions and code changes you'd recommend to make this better!

**Comment by tykishore-snowflake** [comment]
Thank you @sfc-gh-jhansen. It would be great to have features like Deployment validation and rollback etc by leveraging snowflakes ground breaking features? Would those be an additional script or do we have any other mechanism by which we can achieve this?

**Comment by sfc-gh-jhansen** [comment]
Yes, I agree that those would be nice features, and am happy to work with anyone interested in adding those features. Rollbacks can be tricky and most DCM tools have many warnings about the usefulness in practice. But as for Snowflake's incredible features like Cloning and Time Travel that can certainly be leveraged as part of the larger release process (i.e. clone a new environment before testing/validating your scripts, or using Time Travel in the event of a rollback). Again happy to collaborate with anyone willing to take this on.

**Comment by yadutata** [comment]
Firstly thank you for all the help you are doing to community. Customers love the simplicity of the product and problems they see overcome with this. A Big thank you for this. Yes, Would love to contribute. Lets connect
