### ISSUE TITLE
Creating table throwing a SQL compilation error due to syntax error

### ISSUE THREAD

**Issue by abigailknoble** [Snowflake-Labs/schemachange#32]
**Getting error when trying to create any table:** 
snowflake.connector.errors.ProgrammingError: 001003 (42000): SQL compilation error:
syntax error line 1 at position 0 unexpected '﻿C'.

**Even extremely simple tables:**
CREATE TABLE HELLO_WORLD
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);

**Comment by bidutch** [comment]
my experience is that adding explicit database and schema notations to the script reduce the chances of failures, so in this case either a USE DATABASE and USE SCHEMA or CREATE TABLE database.schema.HELLO_WORLD would be a first thing for me to try

**Comment by abigailknoble** [comment]
**I've tried that as well.** 

USE SCHEMA db.schema;
CREATE OR REPLACE TABLE schema.newtable
(
columns VARCHAR
);

**Regardless of what first character is, or seemingly anything else in the file, I get:**
snowflake.connector.errors.ProgrammingError: 001003 (42000): SQL compilation error:
syntax error line 1 at position 0 unexpected...

**Comment by bidutch** [comment]
and the query does execute in Snowflake using the same role ? And other staments (INSERT, etc) execute with or without this error ?

**Comment by sfc-gh-jhansen** [comment]
Hey there @abigailknoble and @bidutch, thanks for the feedback. I've seen a few similar issues, but most have been related to special characters in the scripts themselves. I would recommend creating new script files, with a standard text editor, and try manually typing script contents yourselves. Most of the time it's related to special characters in the scripts.

**Comment by Manocs11** [comment]
we have .csv file in date column that .csv we have to load data to snowflake using python . in this case how to mention the date column in datatype . i have mentioned py code as """create or replace schema.tb1 ( join_date date, name varchar);"""

if i ran py im getting error like 


  File ~\AppData\Roaming\Python\Python310\site-packages\snowflake\connector\errors.py:221 in default_errorhandler
    raise error_class(

ProgrammingError: 001003 (42000): SQL compilation error:
syntax error line 1 at position 47 unexpected '100'.
