### ISSUE TITLE
Introducing a different way of version control for scripts

### ISSUE THREAD

**Issue by bidutch** [Snowflake-Labs/schemachange#33]
We are currently implementing Snowchange as-is, and are now at the intersection of scaling up (multiple teams/projects). The current way of versioning that Snowchange uses will not be an option imho, as feature branches from multiple teams will exists in parallel and for longer and/or shorter time, this causing possible conficts in executed scripts that have higher version that scripts still in a feature branch.

Our plan is to change to a versioning on file level content instead of existing in the name of the file. Example, where the first line of a script can be:
-- version: 1
SELECT ...
-- end script
When a developer works in a feature branch, changes to the script will include a change to:
-- version: 2
SELECT ....
-- end script

This will offcourse mean scripts need to be composed differently by the developers, and ALTER TABLE type code needs to be included in the way of working as well, probably by means of pre- or postdeployment scripts.

I realise that this gears more towards a declarative way of working and that possibly most of the current Snowchange script needs to be redeveloped. We will probably start with a fork, I am looking forward to see if more organisations might find this an interesting way to scale with Snowchange. Also offcourse very curious to hear from the original developers how they feel about this approach. Perhaps a change from filename based versioning to in-file versioning might be easier to build than I am thinking now ?

**Comment by sfc-gh-jhansen** [comment]
Hey there @bidutch, thanks for the feedback. But I'm not sure how this is really any different than the script naming convention. In either scenario there is the possibility for a merge conflict, either file name or file contents. In either scenario there needs to be communication or process to handle the possible conflict. Can you please help me understand how this scenario solves the possible conflict between parallel branches?

**Comment by bidutch** [comment]
Hi @sfc-gh-jhansen, I have multiple teams working on feature branches, added an image to clarify. 
![image](https://user-images.githubusercontent.com/11424878/111958492-9795ef00-8aed-11eb-8bd5-9f70d270c7b3.png)
With multiple teams, in orde to get clear communication about versioning, teams will need to start working on a specific version, e.g. team B is the first on, they pick version 6, team A comes after and picks version 7. Since team A is finished earlier, the code is executed and the highest version in the CHANGE_HISTORY table will be version 7, causing version 6 never to be executed via Snowchange. This way of working is required because indeed having two versions 1.4 will cause a runtime exection error in Snowchange. With the proposed solution, we try to bring eliminate the possibility of code not being executed.

**Comment by sfc-gh-jhansen** [comment]
Thanks for sharing. But I'm still not clear how moving the version number into the script (from being in the filename) solves the problem. Either way you have the possibility of the versions in the feature branches getting out of order with respect to the development or master branches. It seems to me like the reality of working with an incremental style DCM tool.

But would love to see what you come up with. That will likely help me better understand the idea.

**Comment by michael-robbins** [comment]
You'd probably have to think about having distinct Snowflake environments for each feature branch as a 'push the complexity to another abstraction'?

You could also look into multiple change tables if each feature branch is only dealing with 'new' objects in a shared Snowflake environment? Then on merge of the PR you'd go and revert back each feature branches objects and apply it through the core change table?

Not sure there's a super easy way here given you're dealing with a shared environment and having multiple teams independently incrementing the 'single shared change table'.

**Comment by MACKAT05** [comment]
@bidutch  @michael-robbins  Please check if the functionality I added in my fork.  vars , and project history table's definition can be side loaded in a file location inside a repository or repository fork, this would allow the management of environment defs to be pushed into VARS and compared across projects for conflicts.
