### ISSUE TITLE
Cannot get this pip installed .. tried on Python 3.9.1 and 3.6.6

### ISSUE THREAD

**Issue by gtalton** [Snowflake-Labs/schemachange#39]
Both Python versions a simple pip install will error out with:

  ERROR: Could not find a version that satisfies the requirement pyarrow<0.18.0,>=0.17.0
  ERROR: No matching distribution found for pyarrow<0.18.0,>=0.17.0

**Comment by gtalton** [comment]
Oh and I also tried a completely clean virtualenv on the Python 3.9.1 version .. same symptom.

**Comment by sfc-gh-jhansen** [comment]
Hi there @gtalton, please check out the "Prerequisites" section in the schemachange documentation: https://github.com/Snowflake-Labs/schemachange#running-schemachange. There is actually a new PR that enables Python 3.9.x which should be released shortly, so stay tuned on that.

**Comment by gtalton** [comment]
Yep, I see my Python version isn't supported, my bad. I was able to roll back a Python 3.6.6 I had on my laptop and it just worked so thank you for pointing that out! 

Regards,
Gerald

**Comment by sfc-gh-jhansen** [comment]
No worries @gtalton, and I just published a new version of schemachange which supports Python 3.9.x so you should be good to go with a new Python version!
