### ISSUE TITLE
Schema names starting with a number are not created

### ISSUE THREAD

**Issue by marcogatto1** [Snowflake-Labs/schemachange#40]
When running schemachange on schemas starting with a number (i.e. 1xyzzz) the following error is raised:
`SQL query: CREATE SCHEMA IF NOT EXISTS 1xyzzz
Traceback (most recent call last):
  File "schemachange/schemachange/cli.py", line 366, in <module>
    main()
  File "schemachange/schemachange/cli.py", line 363, in main
    schemachange(args.root_folder, args.snowflake_account, args.snowflake_user, args.snowflake_role, args.snowflake_warehouse, args.snowflake_database, args.change_history_table, args.vars, args.create_change_history_table, args.autocommit, args.verbose, args.dry_run)
  File "schemachange/schemachange/cli.py", line 80, in schemachange
    create_change_history_table_if_missing(change_history_table, snowflake_session_parameters, autocommit, verbose)
  File "schemachange/schemachange/cli.py", line 294, in create_change_history_table_if_missing
    execute_snowflake_query(change_history_table['database_name'], query, snowflake_session_parameters, autocommit, verbose)
  File "schemachange/schemachange/cli.py", line 248, in execute_snowflake_query
    raise e
snowflake.connector.errors.ProgrammingError: 001003 (42000): SQL compilation error:
syntax error line 1 at position 28 unexpected '1'.
syntax error line 1 at position 44 unexpected '<EOF>'.`

Snowflake workaround for these cases is to use the double quote, example:
CREATE SCHEMA IF NOT EXISTS "1xyzzz"

Maybe a possible resolution for this issue is to always put double-quotes before and after schema names.

**Comment by sfc-gh-jhansen** [comment]
Yes, this is the expected default behavior in Snowflake. Please see the [Identifier Requirements](https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html) for more details. While it's possible to use quoted identifiers in Snowflake I would not want to make that the default. When using quoted identifiers to create objects those identifiers become case sensitive which can cause many unforeseen errors by developers and analysts alike.

In this case I would suggest renaming your schemas, or if you absolutely must name them that way then fork your own version of schemachange for your use.

Hope that helps!
