### ISSUE TITLE
Fixture data generator based on schema

### ISSUE THREAD

**Issue by carlosmmelo** [Snowflake-Labs/schemachange#47]
Is there a way of generating fixture data pragmatically based on the schema definitions?

I used to use Redshift and Postgres and we built a customer scripts in python that generates data base on the schema updates/changes since both development and tests depends on the,.

**Comment by sfc-gh-jhansen** [comment]
Hi there @carlosmmelo, thanks for reaching out. I'm not sure I understand the goal here (and it looks like your description may have been cut off). What exactly are you trying to generate? And how would it tie to your schemachange change scripts?

**Comment by carlosmmelo** [comment]
lets say you have couple of tables where programmatically we could generate fixture data to all our tables and columns, when an updates happens to the schema (by removing or adding columns) the generator should be able to read that change (from a github repo where we store the schemas) and generate data for those new columns  as well (this is typically just for tests environments)

**Comment by sfc-gh-jhansen** [comment]
I guess this really depends on the generating tool you're using. As they're often separate tools I can see how it might be challenging to connect the two, especially with an imperative-style tool like schemachange. Nothing comes to mind immediately for ways to change schemachange to support this, while remaining a simple, generic tool. Do you have any ideas of how this might be accomplished?
