### ISSUE TITLE
Dry run

### ISSUE THREAD

**Issue by priya789** [Snowflake-Labs/schemachange#48]
Hello,

This is not for any new  issue, but I want to ask a query regarding snowchange.
I am using an older version if snowchange and have just recently found out, it has been renamed to schemachange and also I can see something called as dry run in the cli.py script.

could someone help me to understand what are the changes and upgrades done from older versions to this?

**Comment by sfc-gh-jhansen** [comment]
Hi there @priya789, thanks for reaching out! Please check out the [project documentation](https://github.com/Snowflake-Labs/schemachange) for details on the newish dry run feature as well as our [CHANGELOG](https://github.com/Snowflake-Labs/schemachange/blob/master/CHANGELOG.md) for a complete list of changes to the tool.
