### ISSUE TITLE
Adding checksum checking to repeatable change scripts

### ISSUE THREAD

**Issue by BoAustin** [Snowflake-Labs/schemachange#49]
Hello,

Is there a plan to mimic the behavior of flyway's [repeatable migration](https://flywaydb.org/documentation/concepts/migrations.html#repeatable-migrations) functionality regarding verifying the checksum changes before re-applying the repeatable change script?

Our use case will involve having many repeatable scripts full of stored procedures and functions and when Snowpark comes out this is going to explode and it would be great if we didn't have to re-apply the code that didn't change each time we ran schemachange.

**Comment by sfc-gh-jhansen** [comment]
Hey there @BoAustin, I think that's a great idea. As you pointed out schemachange doesn't currently make use of the checksums. If you're willing, please submit a PR with those changes and I'll take a look. Thanks!

**Comment by AuelJonas** [comment]
Hi @BoAustin , 
I created the code for this issue :)

**Comment by sfc-gh-jhansen** [comment]
Just published this change under 3.0.0
