### ISSUE TITLE
Running Script on DOCKER  Container

### ISSUE THREAD

**Issue by sairamthejavacoder** [Snowflake-Labs/schemachange#50]
It is unable to recognize the SQL scripts from given  directory

 for example:

folder structure for scripts : C:\Snowflake_CICD_new\schemachange\demo\aggregated\V1__cherry.sql  --- where SQL Files Saved.

  docker run -it --rm `
   --name snowflake_cicd_new `
   -w /usr/src/schemachange  `
   -e SNOWFLAKE_PASSWORD='XXXXXX' `
   python:3 /bin/bash -c "pip install schemachange --upgrade && schemachange  -f demo/aggregated/  -a XXXXXX -u XXXXX  -r XXXXX -d DEMO_DB -w COMPUTE_WH --create-change-history-table"

![image](https://user-images.githubusercontent.com/84699609/122556942-c161a200-d059-11eb-936b-6cb1667aa10b.png)

**Comment by MACKAT05** [comment]
you might want to redact the log screenshot.  also change V1__cherry.sql to R__cherry.sql to repeat on each run or  V__1__cherry.sql to run only once. the way you have named your files is causeing that script to not be recognized

**Comment by sfc-gh-jhansen** [comment]
Hmm, not exactly sure what's going on @sairamthejavacoder. But you can see in the output that schemachange clearly identifies the root folder (passed in via the -f argument), which is super helpful for debugging these kinds of issues. In general you should be passing the absolute path to the root folder (via the -f argument), not a relative path. Hopefully that helps you get to the bottom of it.
