### ISSUE TITLE
Upgraded functionality

### ISSUE THREAD

**Issue by MACKAT05** [Snowflake-Labs/schemachange#51]
I'm working with the State of California Department of technology to use this in their CI/CD pipelines and its quite painful to define Vars in the way it has been shown in examples.

I have prepared changes that allow the vars to be stored in a file in the repository (or anywhere) and added an option to specify a Key in the Vars to contain the change history table.

We need this to allow concurrent deployments to maintain their own environment definitions and change history without constant pipeline revision.

**Comment by MACKAT05** [comment]
added pull request

**Comment by sfc-gh-jhansen** [comment]
Follow this in https://github.com/Snowflake-Labs/schemachange/pull/55
