### ISSUE TITLE
Any support for templates? 

### ISSUE THREAD

**Issue by jcollum** [Snowflake-Labs/schemachange#53]
We'd like to create some warehouses that have the environment name in the name of the warehouse: PRD_ACCOUNTS for instance. Anyway to accomplish this in schemachange or will we need to `sed` it?

**Comment by MACKAT05** [comment]
What is the situation exactly, maybe you can you add 'USE WAREHOUSE {{ VAR_WAREHOUSE }};' to the top of appropriate scripts?  then use the PRD_ACCOUNTS  as a value in tour VARS input if its a Runtime issue or is this more you want schema change to iterate over a single script like a run many command?

**Comment by jcollum** [comment]
Prd_warehouse
Int_warehouse
Dev_warehouse

I found the variables section of the docs, that's close enough

**Comment by sfc-gh-jhansen** [comment]
Yep, variables are the way to handle that scenario.
