### ISSUE TITLE
Schema Change Fails with an error ( Multiple instances of same file)

### ISSUE THREAD

**Issue by yadutata** [Snowflake-Labs/schemachange#61]
while executing schema change with only two files ( V1.1__firstscript.sql,V1.2__secondscript.sql) we are getting an error that script version 1.1.1 exists more than once. We checked multiple times in the location of the scripts we do have only one instance of the file. Attached is the screenshot. Appreciate any help on this. 
<img width="674" alt="Screen Shot 2021-07-22 at 5 01 17 PM" src="https://user-images.githubusercontent.com/23000353/126714642-bf52f96e-cd81-4f92-b28a-0205e4d2a70d.png">

**Comment by sfc-gh-jhansen** [comment]
Hi there @yadutata, thanks for providing the feedback. As far as I know this error means that you have multiple files somewhere in the root project folder with the same version number. I would try running schemachange with “-v” and see if that gives you the clue. Also please try running schemachange with the ‘-f’ or ‘--root-folder’ and try pointing it to an empty folder.
