### ISSUE TITLE
Escaping ' in vars json

### ISSUE THREAD

**Issue by 2ndway** [Snowflake-Labs/schemachange#62]
Hi,

We would like to pass 'xxx' as a variable. Escaping ' doesn't seem to be possible in the vars json.
Any help is highly appreciated.

**Comment by sfc-gh-jhansen** [comment]
Hey @2ndway, thanks for the feedback. I haven't run into this issue before. Any ideas on what code changes would be required here? Happy to review a PR if you submit one.

**Comment by sfc-gh-jhansen** [comment]
Hey @2ndway, I just published version 3.1.0 which supports passing arguments and variables via a YAML config file. Please check out the README for more details. Hope that helps!
