### ISSUE TITLE
Version handling with Multiple Directories

### ISSUE THREAD

**Issue by mhan92** [Snowflake-Labs/schemachange#64]
Hello, 

Is it possible to have the version numbering be unique to a specific directory path instead of the entire database folder?

For example
For example
(project_root)
|
-|-- table_1 -- directory to the specific schema
**|-- V1.1.1__first_change.sql
**|-- V1.1.2__second_change.sql
**|-- R__sp_add_sales.sql
**|-- R__fn_get_timezone.sql
|-- production_database
*|-- schema_2
**|-- table_1
***|-- V1.1.1__third_change.sql -- repeated version number but unique to directory
***|-- R__fn_sort_ascii.sql

thanks

**Comment by mhan92** [comment]
Another request, is it possible to have the max version check against the schemachange history table to refer the the description as well as the version number? 

Does this mean we always have to increment the versions when we are making changes to the same table?

**Comment by sfc-gh-jhansen** [comment]
Hi there @mhan92, thanks for the questions. Imperative style database change management tools depend on the concept of versioned changes. Those can be managed by version numbers (schemachange and Flyway) or a dependency mapping file (Sqitch). If you want to have two separate sets of scripts each with their own version numbers you can do that currently by running schemachange against the two different project folders (-f) and by specifying a different change history table for each. Hope that helps.
