### ISSUE TITLE
Q: option for authenticator

### ISSUE THREAD

**Issue by tkang007** [Snowflake-Labs/schemachange#66]
Hi There,
Thanks for your effort for the helpful open source tool, snowflake schemachange.
We are using athenticator, Okta app and cannot find option in schemachange.
Could you give me some help?

**Comment by sfc-gh-jhansen** [comment]
Right now schemachange does not support Okta, only Snowflake password and key pair authentication. Since schema change is primarily run in a non-interactive, service account way I'm not sure how useful this would be. Can you use key pair auth with a service account?
