### ISSUE TITLE
Compaison

### ISSUE THREAD

**Issue by 2020testuser** [Snowflake-Labs/schemachange#68]
Hi,
Could you please let me know whether someone did any tools comparison with Fireway - https://github.com/kevlened/fireway and SchemaChange? If so, could you please share the details? Thanks!

**Comment by sfc-gh-jhansen** [comment]
Hi there @2020testuser, Fireway looks to be a database change management tool for Google Firestore. schemachange is a database change management tool for Snowflake. Hope that helps.

**Comment by 2020testuser** [comment]
@sfc-gh-jhansen - Thanks! I meant [Flyway](https://flywaydb.org/)  and not Fireway. How schemachange is different from flyway? Was any feature comparison done. Could you please share? Thanks in advance!
