### ISSUE TITLE
Repeatable scripts don't work in the version 3.0.0

### ISSUE THREAD

**Issue by arkhipkin** [Snowflake-Labs/schemachange#69]
Now repeatable scripts don't work: if you try to execute a folder with a single `R__` script - it says:
```
schemachange version: 3.0.0
Using change history table METADATA.SCHEMACHANGE.CHANGE_HISTORY (last altered 2021-09-13 17:07:29.614000+02:00)
Max applied change script version: XXX
Successfully applied 0 change scripts (skipping 1)
```

We were needed to rollback to previous version (`pip install schemachange==2.9.2`) to get expected behaviour of the tool.

**Comment by sfc-gh-jhansen** [comment]
Hi there @arkhipkin, please check out the [CHANGELOG](https://github.com/Snowflake-Labs/schemachange/blob/master/CHANGELOG.md) for details about what changed in version 3.0.0. There was a bug in the logic for Repeatable scripts which was changed in 3.0.0. Now Repeatable scripts are only re-run with the contents of the script change. To achieve the same prior behaviour we introduced the new "A" scripts which always run even if the contents of the script haven't changed. Hope that helps.

**Comment by arkhipkin** [comment]
thank you for the explanations @sfc-gh-jhansen
