### ISSUE TITLE
Comparison  on CI/CD tools

### ISSUE THREAD

**Issue by 2020testuser** [Snowflake-Labs/schemachange#70]
Sorry. Since, my issue got closed and unable to reopen, opening this new issue.

@sfc-gh-jhansen - Thanks! I meant [Flyway](https://flywaydb.org/) not Fireway. How schemachange is different from flyway? Was any feature comparison done. pros and cons in each? Could you please share? 

I'm assuming since schemachange is from SnowFlake , it should have more capabilities and must work better than flyway. I might be wrong. 

Thanks in advance!

**Comment by sfc-gh-jhansen** [comment]
Hey there @2020testuser. Flyway is a great, mature tool that is written in Java and supports many different databases. schemachange is a simple, lightweight, Python script that only works with Snowflake. schemachange borrows the naming convention for scripts from flyway but doesn't support all the features of Flyway (some of which you have to pay for). For more details please compare the documentation. Hope that helps.
