### ISSUE TITLE
Max high water mark

### ISSUE THREAD

**Issue by 2ndway** [Snowflake-Labs/schemachange#82]
Hi,

We would be interested in a max water mark to supply with others deliverables or within build artifacts to execute the corresponding db changes instead of using pull requests for this.

Let’s say I have V1 to V200 script in my repo. On my Dev I execute all of them to go with my Java app but on prod I want to execute only up to V180 to assure compatibility with my Java ap version I have there.
So a Parameter to pass within my deployment to restrict to a max version would be great.

BR

**Comment by sfc-gh-jhansen** [comment]
Hey there @2ndway, thanks for reaching out. This is generally handled with your branching and release strategy. Depending on how you handle your dev environment, it often has many inflight changes from different developers. But what goes through test/qa to prod is generally much more controlled and the need you described is addressed. That's what I've seen with many customers. Can it not be managed through a branching/release strategy?

**Comment by sfc-gh-tmathew** [comment]
@2ndway 
The branching strategy is the most common pattern to ensure only tested code gets executed in production. 

We would like to close the issue because we do not plan to add this functionality. 

Thank you for using schemachange.

Please open a new issue based on the latest code base.
