### ISSUE TITLE
Question/Clarification

### ISSUE THREAD

**Issue by tsingh2k15** [Snowflake-Labs/schemachange#83]
I am evaluating the tools which I could use for automating workflow for snowflake schema migrations with in my CI/CD. I am curious to learn more about this tool and how this tool differs from flyway? What could be the value add for end users like myself If I want to use this tool instead of Flyway? I am going through the README to begin with. Any more information that could be shared would be helpful.

**Comment by sfc-gh-jhansen** [comment]
Hey there @tsingh2k15, please check out my [Snowflake DevOps Recommendation](https://developers.snowflake.com/resources/?wvideo=haqeh4q2se) video for more details. Thanks!
