### ISSUE TITLE
Variables are not reading by schemachange

### ISSUE THREAD

**Issue by devopsimus** [Snowflake-Labs/schemachange#94]
Please do something with variables, I cannot pass $variable in --vars '{'var1': '$variable'}'
I have a bash script that looping areas in Snowflake
                    for areaName in $Snowflake.AreaNames
                    do
                      echo "Running schemachange for area $areaName"
                      schemachange -f $(System.DefaultWorkingDirectory)/scripts/${{ parameters.Environment }}/area -a $(Snowflake.AccountName) -u $(Snowflake.DeployUser) -r $(Snowflake.DeployRole) -w $(Snowflake.DeployWarehouse) -d '' -c $(Snowflake.HistoryTable) --vars '{"ORG_NAME": "$(Snowflake.Organization)", "AREA_NAME": "$areaName"}'
                    done

And I cannot pass the variable value to here

**Comment by sfc-gh-jhansen** [comment]
Hey there @devopsimus, I just tested on the command line and it works for me to pass variables using the --vars argument. It looks like it may be an issue with your bash script. I did a quick Google search and it looks like [$(...) and other forms of substitutions are not interpolated in single-quoted strings](https://stackoverflow.com/questions/23655580/in-bash-how-do-i-interpolate-in-a-string). Hope that helps.
