### ISSUE TITLE
make change history optional

### ISSUE THREAD

**Issue by tomKneitas** [Snowflake-Labs/schemachange#98]
Currently when you're specifying "change-history-table: null", it would still use/create the default table in METADATA database. There are some use cases, when you don't need to track history, such as schema or db  cloning, which could be achieved with "always" scripts alone in a separate root-folder from regular DDL's. 

In this particular use case, the information usefulness you're getting from the change history is small compared with the time it takes to put it there.

In this example, we're using the metadata change_history table, because we don't want to pollute our versioned tables. 

![image](https://user-images.githubusercontent.com/84454601/141278442-0df9c3fc-4eac-444f-a424-4559b19b7032.png)

**Comment by sfc-gh-jhansen** [comment]
Hey @tomKneitas, thanks for the feedback. I'll have to think more about it but as you pointed out schemachange logs every script execution (V, R, or A) to a change history table. Not exactly sure how a disable switch would work. For example what if someone has a V or R script in their project folder? If so we need the change history table. Not sure how we would know without scanning all the scripts, checking for V or R scripts, and only skipping if there were only A scripts.

Is the problem just that the change history table has a lot of records? Does that cause a problem?

**Comment by sfc-gh-tmathew** [comment]
@tomKneitas Additionally, if the change to the database does not need to be versioned, then an option is to execute it without schemachange as part of the CI/CD pipeline. 

Thoughts?
